CREATE TABLE utilisateurs (
id INT AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100) NOT NULL,
prenom VARCHAR(100) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
date_naissance DATE,
date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);